### PR TITLE
Fix "Edit on GitHub" link in docs

### PR DESCRIPTION
**Pull request by gdalle**
See https://github.com/JuliaDocs/Documenter.jl/issues/1375
OK, I'll admit it's a low-effort PR ^^

### CODE REVIEW

**Comment by avik-pal** [comment]
The formatter didn't use the .JuliaFormatter, it seems to be using the default one. Try running from REPL in Lux.jl directory

**Comment by gdalle** [comment]
I'll try. But wouldn't it be easier to just run JuliaFormatter during CI? I seem to remember it was possible

**Comment by avik-pal** [comment]
superseded by https://github.com/avik-pal/Lux.jl/commit/4db292676a48a77081d4158e9ec928504fe1a04e

**Comment by gdalle** [comment]
Thanks, sorry I didn’t get there on time

**Pull request closed without merging**
