### PR TITLE
Fix Zygote error caused due to `fill!`

### PR DESCRIPTION
**Pull request by theabhirath**
Zygote doesn't like the mutating `fill!`:

```julia
julia> Zygote.gradient(p -> sum(model(p, ps, st)[1]), x)
ERROR: Mutating arrays is not supported -- called setindex!(::Array{Float32, 3}, _...)
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] (::Zygote.var"#437#438"{Array{Float32, 3}})(#unused#::Nothing)
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/lib/array.jl:71
  [3] (::Zygote.var"#2357#back#439"{Zygote.var"#437#438"{Array{Float32, 3}}})(Δ::Nothing)
    @ Zygote ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67
  [4] Pullback
    @ ./array.jl:350 [inlined]
  [5] (::typeof(∂(fill!)))(Δ::Array{Float32, 3})
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface2.jl:0
  [6] Pullback
    @ ~/.julia/packages/Boltz/scRUZ/src/vision/vit.jl:74 [inlined]
  [7] (::typeof(∂(λ)))(Δ::Tuple{Array{Float32, 3}, Nothing})
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface2.jl:0
  [8] macro expansion
    @ ~/.julia/packages/Lux/0jReB/src/layers/basic.jl:0 [inlined]
  [9] Pullback
    @ ~/.julia/packages/Lux/0jReB/src/layers/basic.jl:523 [inlined]
 [10] (::typeof(∂(applychain)))(Δ::Tuple{FillArrays.Fill{Float32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Nothing})
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface2.jl:0
 [11] Pullback
    @ ~/.julia/packages/Lux/0jReB/src/layers/basic.jl:520 [inlined]
 [12] (::typeof(∂(λ)))(Δ::Tuple{FillArrays.Fill{Float32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Nothing})
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface2.jl:0
 [13] Pullback
    @ ./REPL[6]:1 [inlined]
 [14] (::typeof(∂(#7)))(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface2.jl:0
 [15] (::Zygote.var"#52#53"{typeof(∂(#7))})(Δ::Float32)
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface.jl:41
 [16] gradient(f::Function, args::Array{Float32, 4})
    @ Zygote ~/.julia/packages/Zygote/DkIUK/src/compiler/interface.jl:76
 [17] top-level scope
    @ REPL[6]:1
 [18] top-level scope
    @ ~/.julia/packages/CUDA/GGwVa/src/initialization.jl:52
```

So this is a version using `fill` instead. Sister issue of https://github.com/FluxML/Metalhead.jl/pull/162

### CODE REVIEW

**Comment by avik-pal** [comment]
Can we instead define a function which does the in place fill! and mark it as @non_differentiable? I believe that will be less allocating and prevent an unnecessary gradient propagation

**Comment by theabhirath** [comment]
Just to confirm, you mean something like:

```julia
_fill_like(y::AbstractArray{T, 3}) where {T} = fill!(similar(y, 1, 1, size(y, 3)), one(T))
ChainRulesCore.@non_differentiable _fill_like(y)

function (m::ClassTokens)(x::AbstractArray{T, 3}, ps, st) where {T}
    # Generic Alternative: Repeat is extremely inefficient on GPUs and even in general
    tokens = ps.token .* _fill_like(x)
    return hcat(tokens, x), st
end
```

**Comment by avik-pal** [comment]
Yes

**Comment by avik-pal** [comment]
Can you add dependence on ChainRulesCore (with a compact entry) instead of calling through NNlib? Everything else looks good

**Pull request merged**
