### PR TITLE
Add Lux.@layerdef for easy custom model creation

### PR DESCRIPTION
**Pull request by avik-pal**
## TODOs

- [ ] Highlight what this API cannot do yet
- [ ] Allow more configuration of the models by parsing the keyword arguments
- [x] Add a `contrib` page to documentation
- [ ] Documentation for the Breaking Change
  - [ ]  `update_guide.md`
  - [x] `ecosystem.md`
  - [x] `overview.md`
- [ ] Tests for `@compact`
- [x] Add a syntax to handle shared layers

## Lux.@compact

An Experimental compact API (inspired by `flax.linen.compact` decorator) to make it easier to write Lux models.

### Example

```julia
using Lux, Random, Zygote, NNlib

Lux.@compact function MyCustomModel((x, y)::T) where {T}
    @assert size(x, 1) == 2 && size(y, 1) == 2
    a = Dense(3, 3, relu)(Dense(2, 3)(x) .+ Dense(2, 3, relu)(x)) .- Dense(2, 3, gelu)(x)
    b = Dense(3, 2, sigmoid)(a)
    c = Dense(2, 2, relu)(y)
    return b .+ c
end

model = MyCustomModel()

ps, st = Lux.setup(Random.default_rng(), model)
x, y = randn(Float32, 2, 1), randn(Float32, 2, 1)

model((x, y), ps, st)
```

### Generated Model

```julia
quote
    struct MyCustomModel{__dense_1_type, __dense_2_type, __dense_3_type, __dense_4_type, __dense_5_type, __dense_6_type} <: Lux.AbstractExplicitContainerLayer{(:dense_1, :dense_2, :dense_3, :dense_4, :dense_5, :dense_6)}
        dense_1::__dense_1_type
        dense_2::__dense_2_type
        dense_3::__dense_3_type
        dense_4::__dense_4_type
        dense_5::__dense_5_type
        dense_6::__dense_6_type
    end
    function MyCustomModel(; )
        return MyCustomModel(Dense(3, 3, relu), Dense(2, 3), Dense(2, 3, relu), Dense(2, 3, gelu), Dense(3, 2, sigmoid), Dense(2, 2, relu))
    end
    function (mandrill::MyCustomModel)((x, y)::T, ps::Union{Lux.ComponentArray, NamedTuple}, st::NamedTuple; ) where T
        if size(x, 1) == 2 && size(y, 1) == 2
            nothing
        else
            Base.throw(Base.AssertionError("size(x, 1) == 2 && size(y, 1) == 2"))
        end
        (wildebeest, camel) = mandrill.dense_4(x, ps.dense_4, st.dense_4)
        (antelope, gaur) = mandrill.dense_3(x, ps.dense_3, st.dense_3)
        (rhinoceros, ibis) = mandrill.dense_2(x, ps.dense_2, st.dense_2)
        (mallard, jellyfish) = mandrill.dense_1(rhinoceros .+ antelope, ps.dense_1, st.dense_1)
        a = mallard .- wildebeest
        (hamster, monkey) = mandrill.dense_5(a, ps.dense_5, st.dense_5)
        b = hamster
        (wasp, sanddollar) = mandrill.dense_6(y, ps.dense_6, st.dense_6)
        c = wasp
        return (b .+ c, NamedTuple{(:dense_1, :dense_2, :dense_3, :dense_4, :dense_5, :dense_6)}((jellyfish, ibis, gaur, camel, monkey, sanddollar)))
    end
end
```

### CODE REVIEW

**Comment by ToucheSir** [comment]
Though it uses a different set of DSLs, I believe the metaprogramming involved in https://chengchingwen.github.io/Transformers.jl/dev/stacks/ should be similar. Is it possible to express tied weights using this or is that a non-goal?

**Comment by avik-pal** [comment]
@ToucheSir  tied weights should actually be easier to handle since you don't need to rewrite the function call signatures

**Comment by ToucheSir** [comment]
to clarify, are you saying that:
```
Lux.@compact function MyCustomModel((x, y)::T) where {T}
    @assert size(x, 1) == 2 && size(y, 1) == 2
    shared = Dense(2, 3, gelu)
    a = Dense(3, 3, relu)(shared(x) .+ Dense(2, 3, relu)(x)) .- shared(x)
    b = ...
end
```
Should just work?

**Comment by avik-pal** [comment]
No all layer calls must be complete at the moment (so there are models which can't be expressed). I should write out what the current implementation can and cannot do.

**Comment by avik-pal** [comment]
Not sure what is going on here but
```julia
Lux.@compact function CorrectReturn(x)
    x = Dense(2, 2)(x)
    return x
end
```
gives `ERROR: syntax: function argument and static parameter names must be distinct around REPL[33]:1`, though copy pasting the generated code in the REPL seems to work fine

**Pull request closed without merging**
