### PR TITLE
Generic recurrent cells

### PR DESCRIPTION
**Pull request by jumerckx**
context: #135
My first attemt at making recurrent cells more generic. Locally, tests pass. I haven't yet changed docstrings or the LSTM example, I'll gladly do so if the API changes are OK.

### CODE REVIEW

**Comment by avik-pal** [comment]
The API changes lgtm

**Comment by jumerckx** [comment]
All relevant docstrings and examples should be updated now.

**Comment by avik-pal** [comment]
Run formatting and we should be good to merge

**Comment by jumerckx** [comment]
Done :)

**Review by avik-pal — APPROVED** [review]

**Pull request merged**
